version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "test_db"
      POSTGRES_USER: "test_db"
      POSTGRES_PASSWORD: "topsecret1"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"